# Site/SEO settings
email: crcorrell@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Chris Correll
title: Emoji (LED) Earrings
description: >
  ACAB
url: ACAB
twitter_username: 
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: ACAB
  - name: instagram
    url: ACAB
  - name: linkedin
    url: ACAB
  - name: github
    url: ACAB
  - name: codepen
    url: ACAB

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: 
mailchimp_input: 

# Author settings
author:
  - name: Chris Correll
    bio: ACAB 
    url: 

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 100
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'ACAB'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
